git:
    depth: 1

cache:
    directories:
        - $HOME/.composer

sudo: false

language: php

notifications:
    email: false

matrix:
    include:
        - php: '7.1'
          install: composer update --prefer-lowest
        - php: '7.1'
        - php: '7.2'
        - php: '7.2'
          install: composer require --dev php-coveralls/php-coveralls
          script: composer phpunit -- --coverage-clover=build/logs/clover.xml
          after_success: vendor/bin/php-coveralls

before_install:
    - composer self-update --stable
    - composer global show hirak/prestissimo -q || composer global require hirak/prestissimo

install: composer install

script: composer check
