git:
    depth: 1

cache:
    directories:
        - $HOME/.composer/cache

sudo: false

language: php

notifications:
    email: false

matrix:
    include:
        - php: '7.1'
          install: composer update --prefer-lowest
        - php: '7.1'
        - php: '7.2'
          env: RUN_PHPSTAN=true
          install: composer require --dev phpstan/phpstan phpstan/phpstan-strict-rules

before_install:
    - composer self-update --stable

install:
    - composer install

script:
    - vendor/bin/phpcs --report-full --standard=PSR2 src tests
    - vendor/bin/php-cs-fixer fix --config=tests/php-cs-fixer.config.php --diff --dry-run
    - vendor/bin/phpunit -c tests/phpunit.xml
    - if [[ $RUN_PHPSTAN ]]; then vendor/bin/phpstan analyse --configuration=tests/phpstan.neon --level=max src; else exit 0; fi
