#!/usr/bin/env php
<?php

foreach ([__DIR__ . '/../../autoload.php', __DIR__ . '/vendor/autoload.php'] as $file) {
    if (file_exists($file)) {
        require_once $file;
        break;
    }
}

$application = new Symfony\Component\Console\Application();
$command = new ComposerJsonFixer\Command\FixerCommand(basename(__FILE__));

$application->add($command);

$application->setDefaultCommand($command->getName(), true);
$application->run();
